version: '3'
services:
    fib:
        build: .
        expose:
        - "8000"
    nginx:
        image: nginx:1.17
        depends_on:
        - fib
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/ssl:/etc/nginx/ssl:ro
        ports:
        - "80:80"
        - "443:443"
